# OpenWeatherMap API Key
allcrops=['BARLEY','CORN','COTTON','GRAIN','HAY','HAYLAGE',
 'OATS','PEANUTS','RYE','SOYBEANS','WHEAT','GRASSES',
 'LEGUMES','PEAS','SORGHUM','SESAME','SUNFLOWER','HERBS','CANOLA','BEANS','BUCKWHEAT',
 'MINT','JOJOBA','CHICKPEAS','RICE','CAMELINA','MILLET','MAPLE SYRUP','HOPS','SAFFLOWER',
 'POPCORN','MUSTARD','TRITICALE','WILD RICE','DILL','SUGARBEETS','TARO','LENTILS',
 'FLAXSEED','TOBACCO','RAPESEED','SUGARCANE','SWITCHGRASS','MISCANTHUS','GUAR',
 'APPLES','BERRY TOTALS','BLUEBERRIES','FIGS','GRAPES','NECTARINES','NON-CITRUS','ORCHARDS',
 'PEACHES','PEARS','PECANS','PLUMS','TREE NUT','PERSIMMONS','BLACKBERRIES','CITRUS TOTALS',
 'GRAPEFRUIT','LEMONS','LIMES','POMEGRANATES','RASPBERRIES','TANGERINES','CHESTNUTS','APRICOTS',
 'STRAWBERRIES','ALMONDS','HAZELNUTS','KUMQUATS','NON-CITRUS','ORANGES','CHERRIES','ELDERBERRIES',
 'TANGELOS','WALNUTS','ARONIA BERRIES','BERRIES','PASSION FRUIT','KIWIFRUIT','PLUM-APRICOT HYBRIDS','OLIVES',
 'GUAVAS','CURRANTS','PISTACHIOS','DATES','CITRUS','BOYSENBERRIES','AVOCADOS','MACADAMIAS',
 'LOGANBERRIES','PRUNES','CHERIMOYAS','PAPAYAS','BANANAS','COFFEE','MANGOES','CRANBERRIES','PINEAPPLES',
 'BEANS','CUCUMBERS','EGGPLANT','GREENS','MELONS','OKRA','PEAS','PEPPERS','POTATOES','PUMPKINS','SQUASH','SWEET CORN',
 'SWEET POTATOES','TOMATOES','TURNIPS','VEGETABLES','CABBAGE','ONIONS','BROCCOLI','LETTUCE',
 'BEETS','CARROTS','SPINACH','RADISHES','GARLIC','HERBS','ASPARAGUS','BRUSSELS SPROUTS','ESCAROLE','CAULIFLOWER',
 'GINGER ROOT','HORSERADISH','GINSENG','CELERY','PARSLEY','RHUBARB','DAIKON','ARTICHOKES','WATERCRESS','CHICORY']

all_crops=[ i.capitalize() for i in allcrops]